### ISSUE TITLE
白与夜 另一种CSS解法

### ISSUE THREAD

**Issue by enihsyou** [ustclug/hackergame2019-writeups#18]
~愚蠢解法~
之前没有看到body上的style，就直接把图片添加负片效果了😂

```css
img {
  filter: invert(1)
}
```
然后白猫就变成一副很诡异的样子😂
